### ISSUE TITLE
things to do in baltimore

### ISSUE THREAD

**Issue by andrewejaffe** [LieberInstitute/jaffe_onboarding#2]
[Kate and Andrew’s unofficial Baltimore Guide (1).docx](https://github.com/LieberInstitute/jaffe_onboarding/files/3602384/Kate.and.Andrew.s.unofficial.Baltimore.Guide.1.docx)

some of this might be useful for the baltimore tab

**Comment by lcolladotor** [comment]
Closing since this repo is inactive.
